//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPMI_DBEntities : DbContext
    {
        public IPMI_DBEntities()
            : base("name=IPMI_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mDept> mDepts { get; set; }
        public virtual DbSet<tIpmi> tIpmis { get; set; }
        public virtual DbSet<tIpmiAnalisa> tIpmiAnalisas { get; set; }
        public virtual DbSet<tIPMIDetail> tIPMIDetails { get; set; }
    }
}
