//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIpmi
    {
        public int Id { get; set; }
        public string NoIPMI { get; set; }
        public Nullable<System.DateTime> Tgl { get; set; }
        public string Dari { get; set; }
        public string ke { get; set; }
        public string Masalah { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public string Status { get; set; }
        public string FileName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Status1 { get; set; }
        public string Ket { get; set; }
        public string FileName1 { get; set; }
    }
}
