//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIpmiAnalisa
    {
        public int id { get; set; }
        public string NoIPMI { get; set; }
        public string Penyebab { get; set; }
        public string RencanaPerbaikan { get; set; }
        public Nullable<System.DateTime> Target { get; set; }
        public string PIC { get; set; }
        public Nullable<System.DateTime> TglActual { get; set; }
        public string Status { get; set; }
        public string InputByDept { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
